export const LANGUAGE_OPTIONS = [
  {
    id: 'en',
    shortLabel: 'English · KJV',
    label: 'English (KJV)',
    nativeLabel: 'English',
    language: 'English',
    locale: 'en-US',
    availability: 'Bible and core app language bundled',
  },
  {
    id: 'bg',
    shortLabel: 'Български',
    label: 'Bulgarian',
    nativeLabel: 'Български',
    language: 'Bulgarian',
    locale: 'bg-BG',
    availability: 'Bible text bundled; Android voice may need download',
  },
  {
    id: 'ch',
    shortLabel: '中文',
    label: 'Chinese',
    nativeLabel: '中文',
    language: 'Chinese',
    locale: 'zh-CN',
    availability: 'Bible text bundled; Android voice may need download',
  },
  {
    id: 'sp',
    shortLabel: 'Español',
    label: 'Spanish',
    nativeLabel: 'Español',
    language: 'Spanish',
    locale: 'es-ES',
    availability: 'Bible text bundled; Android voice may need download',
  },
  { id: 'ar', shortLabel: 'العربية', label: 'Arabic', nativeLabel: 'العربية', language: 'Arabic', locale: 'ar-SA', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'fr', shortLabel: 'Français', label: 'French', nativeLabel: 'Français', language: 'French', locale: 'fr-FR', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'de', shortLabel: 'Deutsch', label: 'German', nativeLabel: 'Deutsch', language: 'German', locale: 'de-DE', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'pt', shortLabel: 'Português', label: 'Portuguese', nativeLabel: 'Português', language: 'Portuguese', locale: 'pt-BR', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'tr', shortLabel: 'Türkçe', label: 'Turkish', nativeLabel: 'Türkçe', language: 'Turkish', locale: 'tr-TR', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'ur', shortLabel: 'اردو', label: 'Urdu', nativeLabel: 'اردو', language: 'Urdu', locale: 'ur-PK', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'fa', shortLabel: 'فارسی', label: 'Persian', nativeLabel: 'فارسی', language: 'Persian', locale: 'fa-IR', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'id', shortLabel: 'Bahasa Indonesia', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia', language: 'Indonesian', locale: 'id-ID', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'ms', shortLabel: 'Bahasa Melayu', label: 'Malay', nativeLabel: 'Bahasa Melayu', language: 'Malay', locale: 'ms-MY', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'bn', shortLabel: 'বাংলা', label: 'Bengali', nativeLabel: 'বাংলা', language: 'Bengali', locale: 'bn-BD', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'hi', shortLabel: 'हिन्दी', label: 'Hindi', nativeLabel: 'हिन्दी', language: 'Hindi', locale: 'hi-IN', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'it', shortLabel: 'Italiano', label: 'Italian', nativeLabel: 'Italiano', language: 'Italian', locale: 'it-IT', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'nl', shortLabel: 'Nederlands', label: 'Dutch', nativeLabel: 'Nederlands', language: 'Dutch', locale: 'nl-NL', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'ru', shortLabel: 'Русский', label: 'Russian', nativeLabel: 'Русский', language: 'Russian', locale: 'ru-RU', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'ja', shortLabel: '日本語', label: 'Japanese', nativeLabel: '日本語', language: 'Japanese', locale: 'ja-JP', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'ko', shortLabel: '한국어', label: 'Korean', nativeLabel: '한국어', language: 'Korean', locale: 'ko-KR', availability: 'Automatic app translation when online; Android voice may need download' },
  { id: 'sw', shortLabel: 'Kiswahili', label: 'Swahili', nativeLabel: 'Kiswahili', language: 'Swahili', locale: 'sw-KE', availability: 'Automatic app translation when online; Android voice may need download' },
];

export const BUNDLED_BIBLE_LANGUAGE_IDS = ['en', 'bg', 'ch', 'sp'];
export const RTL_LANGUAGE_IDS = ['ar', 'fa', 'ur'];

const CORE_COPY = {
  en: {
    'nav.home': 'Home',
    'nav.bible': 'Bible',
    'nav.learn': 'Learn',
    'nav.prayer': 'Prayer',
    'nav.journey': 'Journey',
    'nav.faith': 'Faith',
    'nav.saved': 'Saved',
    'nav.downloads': 'Downloads',
    'nav.library': 'Library',
    'nav.settings': 'Privacy & settings',
    'settings.language': 'Language',
    'settings.eyebrow': 'Safe & private',
    'settings.title': 'Settings',
    'settings.description': 'You are in control of what this app remembers and reveals.',
    'settings.languageDescription': 'Choose the language for Scripture text and local read-aloud.',
    'settings.languageNote': 'English is the main language. App text is translated automatically when online and cached locally; bundled Bible text remains available offline.',
    'settings.translationPrivacy': 'Only public app text is sent for translation. Private notes, reflections, and typed searches stay on this device.',
    'settings.downloadVoices': 'Manage Android voice languages',
    'settings.downloadVoicesNote': 'Download or update voices from the Android speech engine. The app uses the system/default voice for the selected language.',
    'settings.appearance': 'App appearance',
    'settings.appearanceDescription': 'Choose how the app feels at night',
    'settings.readAloud': 'Read-aloud',
    'settings.readAloudDescription': 'Uses the default installed voice for the selected language.',
    'bible.read': 'Read',
    'bible.eyebrow': 'Read · Plan',
    'bible.title': 'The Bible',
    'bible.description': 'Read slowly. Ask honestly. Let Scripture meet you where you are.',
    'bible.plan': 'Plan',
    'bible.audio': 'Audio',
    'bible.translation': 'Translation',
    'bible.translationOptions': 'Bible translation options',
    'bible.bundledTranslation': 'Bundled with the app',
    'bible.onlineTranslation': 'Translate this chapter when online',
    'bible.compareVariants': 'Compare bundled text variants',
    'bible.currentVerse': 'Current verse',
    'bible.readingSpeed': 'Reading speed',
    'bible.startChapter': 'Start chapter',
    'bible.stop': 'Stop',
    'bible.ready': 'Ready to listen',
    'bible.androidAudio': 'Android Text-to-Speech',
  },
  bg: {
    'nav.home': 'Начало',
    'nav.bible': 'Библия',
    'nav.learn': 'Изучаване',
    'nav.prayer': 'Молитва',
    'nav.journey': 'Път',
    'nav.faith': 'Вяра',
    'nav.saved': 'Запазени',
    'nav.downloads': 'Изтегляния',
    'nav.library': 'Библиотека',
    'nav.settings': 'Поверителност и настройки',
    'settings.language': 'Език',
    'settings.eyebrow': 'Сигурно и поверително',
    'settings.title': 'Настройки',
    'settings.description': 'Вие решавате какво да помни и показва това приложение.',
    'settings.languageDescription': 'Изберете езика за текста на Писанието и местното прочитане.',
    'settings.languageNote': 'Английският е основният език. Текстът на приложението се превежда автоматично при интернет връзка и се съхранява локално; включеният библейски текст остава достъпен офлайн.',
    'settings.translationPrivacy': 'За превод се изпраща само публичен текст от приложението. Личните бележки, размисли и търсения остават на това устройство.',
    'settings.downloadVoices': 'Управление на езиците за гласа на Android',
    'settings.downloadVoicesNote': 'Изтегляйте или обновявайте гласове от системата за говор на Android. Приложението използва гласа по подразбиране за избрания език.',
    'settings.appearance': 'Изглед на приложението',
    'settings.appearanceDescription': 'Изберете как да изглежда приложението през нощта',
    'settings.readAloud': 'Прочитане на глас',
    'settings.readAloudDescription': 'Използва инсталирания глас по подразбиране за избрания език.',
    'bible.read': 'Четене',
    'bible.eyebrow': 'Четене · План',
    'bible.title': 'Библията',
    'bible.description': 'Четете бавно. Питайте искрено. Нека Писанието ви срещне там, където сте.',
    'bible.plan': 'План',
    'bible.audio': 'Аудио',
    'bible.translation': 'Превод',
    'bible.translationOptions': 'Опции за библейски превод',
    'bible.bundledTranslation': 'Вградено в приложението',
    'bible.onlineTranslation': 'Превод на тази глава онлайн',
    'bible.compareVariants': 'Сравни вградените текстови варианти',
    'bible.currentVerse': 'Текущ стих',
    'bible.readingSpeed': 'Скорост на четене',
    'bible.startChapter': 'Начало на главата',
    'bible.stop': 'Стоп',
    'bible.ready': 'Готово за слушане',
    'bible.androidAudio': 'Android Text-to-Speech',
  },
  ch: {
    'nav.home': '首页',
    'nav.bible': '圣经',
    'nav.learn': '学习',
    'nav.prayer': '祷告',
    'nav.journey': '旅程',
    'nav.faith': '信仰',
    'nav.saved': '已保存',
    'nav.downloads': '下载',
    'nav.library': '资料库',
    'nav.settings': '隐私与设置',
    'settings.language': '语言',
    'settings.eyebrow': '安全与隐私',
    'settings.title': '设置',
    'settings.description': '您可以控制应用记住和显示的内容。',
    'settings.languageDescription': '选择经文和本地朗读使用的语言。',
    'settings.languageNote': '英语是主要语言。联网时，应用文本会自动翻译并缓存在本地；内置圣经文本可离线使用。',
    'settings.translationPrivacy': '只有公开的应用文本会被发送进行翻译。私人笔记、反思和输入的搜索内容会保留在此设备上。',
    'settings.downloadVoices': '管理 Android 语音语言',
    'settings.downloadVoicesNote': '从 Android 语音引擎下载或更新语音。应用会使用所选语言的系统默认语音。',
    'settings.appearance': '应用外观',
    'settings.appearanceDescription': '选择夜间使用的外观',
    'settings.readAloud': '朗读',
    'settings.readAloudDescription': '使用所选语言已安装的默认语音。',
    'bible.read': '阅读',
    'bible.eyebrow': '阅读 · 计划',
    'bible.title': '圣经',
    'bible.description': '慢慢阅读，诚实发问，让经文在你所在之处遇见你。',
    'bible.plan': '计划',
    'bible.audio': '音频',
    'bible.translation': '翻译',
    'bible.translationOptions': '圣经翻译选项',
    'bible.bundledTranslation': '应用内置',
    'bible.onlineTranslation': '联网时翻译本章',
    'bible.compareVariants': '比较内置文本版本',
    'bible.currentVerse': '当前经文',
    'bible.readingSpeed': '朗读速度',
    'bible.startChapter': '从本章开始',
    'bible.stop': '停止',
    'bible.ready': '准备聆听',
    'bible.androidAudio': 'Android 文字转语音',
  },
  sp: {
    'nav.home': 'Inicio',
    'nav.bible': 'Biblia',
    'nav.learn': 'Aprender',
    'nav.prayer': 'Oración',
    'nav.journey': 'Camino',
    'nav.faith': 'Fe',
    'nav.saved': 'Guardado',
    'nav.downloads': 'Descargas',
    'nav.library': 'Biblioteca',
    'nav.settings': 'Privacidad y ajustes',
    'settings.language': 'Idioma',
    'settings.eyebrow': 'Seguro y privado',
    'settings.title': 'Ajustes',
    'settings.description': 'Tú controlas lo que esta aplicación recuerda y muestra.',
    'settings.languageDescription': 'Elige el idioma para el texto de las Escrituras y la lectura local.',
    'settings.languageNote': 'El inglés es el idioma principal. El texto de la aplicación se traduce automáticamente cuando hay conexión y se guarda localmente; el texto bíblico incluido sigue disponible sin conexión.',
    'settings.translationPrivacy': 'Solo se envía texto público de la aplicación para traducirlo. Las notas privadas, reflexiones y búsquedas escritas permanecen en este dispositivo.',
    'settings.downloadVoices': 'Administrar idiomas de voz de Android',
    'settings.downloadVoicesNote': 'Descarga o actualiza voces desde el motor de voz de Android. La aplicación usa la voz predeterminada del sistema para el idioma elegido.',
    'settings.appearance': 'Apariencia de la aplicación',
    'settings.appearanceDescription': 'Elige cómo se ve la aplicación por la noche',
    'settings.readAloud': 'Lectura en voz alta',
    'settings.readAloudDescription': 'Usa la voz instalada predeterminada para el idioma elegido.',
    'bible.read': 'Leer',
    'bible.eyebrow': 'Leer · Plan',
    'bible.title': 'La Biblia',
    'bible.description': 'Lee despacio. Pregunta con sinceridad. Deja que las Escrituras te encuentren donde estás.',
    'bible.plan': 'Plan',
    'bible.audio': 'Audio',
    'bible.translation': 'Traducción',
    'bible.translationOptions': 'Opciones de traducción bíblica',
    'bible.bundledTranslation': 'Incluido en la aplicación',
    'bible.onlineTranslation': 'Traducir este capítulo cuando haya conexión',
    'bible.compareVariants': 'Comparar textos incluidos',
    'bible.currentVerse': 'Versículo actual',
    'bible.readingSpeed': 'Velocidad de lectura',
    'bible.startChapter': 'Comenzar capítulo',
    'bible.stop': 'Detener',
    'bible.ready': 'Listo para escuchar',
    'bible.androidAudio': 'Texto a voz de Android',
  },
};

export function getLanguageOption(languageId) {
  const value = String(languageId || '').trim().toLowerCase();
  return LANGUAGE_OPTIONS.find((option) => option.id.toLowerCase() === value || option.locale.toLowerCase() === value) || LANGUAGE_OPTIONS[0];
}

export function isRtlLanguage(languageId) {
  return RTL_LANGUAGE_IDS.includes(getLanguageOption(languageId).id);
}

export function getLanguageCopy(languageId, key, fallback = key) {
  return CORE_COPY[languageId]?.[key] || CORE_COPY.en[key] || fallback;
}

export function isKnownLanguageText(languageId, value) {
  const normalized = String(value || '').trim();
  if (!normalized) return false;
  const englishCopy = CORE_COPY.en || {};
  return Object.entries(CORE_COPY[languageId] || {}).some(([key, copy]) => copy === normalized && (languageId === 'en' || copy !== englishCopy[key]));
}
